namespace: ecommerce-ns

replicas: 5

appDeployment:
  labels:
    app: ecommerce
  name: ecommerce-container

image:
  repository: sukhesh77/ecommerce-app
  tag: v1.0.0
  port: 80

service:
  name: ecommerce-service
  port: 80
  type: LoadBalancer
